### ISSUE TITLE
Welcome to Science_Project Discussions!

### ISSUE THREAD

**Issue by github-bot-for-satyamv7** [MTSOSS/Science_Project#6]
### Discussed in https://github.com/MTSOSS/Science_Project/discussions/5

<div type='discussions-op-text'>

<sup>Originally posted by **SatyamV7** December 14, 2022</sup>

## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

</div>

**Comment by SatyamV7** [comment]
This Tepo is not co,m[letefd uyet

**Comment by github-bot-for-satyamv7** [comment]
> This Tepo is not co,m[letefd uyet

Answer

**Comment by SatyamV7** [comment]
Disscussion closed
