### ISSUE TITLE
How To install react when down loading project from github

### ISSUE THREAD

**Issue by github-bot-for-satyamv7** [MTSOSS/Science_Project#7]
I want to install react node modules folder only as I have the source code

**Comment by SatyamV7** [comment]
You can run `npm install` by opening terminal from selected folder

**Comment by github-bot-for-satyamv7** [comment]
> You can run `npm install` by opening terminal from selected folder

Yes This Worked for me

**Comment by github-bot-for-satyamv7** [comment]
> You can run `npm install` by opening terminal from selected folder

Answer
